name: docautomations
description: "A smart prescription automation app for doctors."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  path_provider_android: ^2.2.15
  provider: ^6.1.0
  pdf: ^3.10.6
  printing: ^5.11.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  intl: ^0.18.0
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.1.0
  in_app_purchase: ^3.2.3
  marquee: ^2.2.3
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  




flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_logo.png"


flutter_native_splash:
  color: "#ffffff"          # background color
  image: assets/icon/app_logo.png
  android: true
  ios: true
  web: false


flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_logo.png
    - images/
    - assets/
